# Generated by Django 4.2.30 on 2026-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
